package ru.raydroid.plugin.host.impl.presentation

object BuiltinIconMappings {
    private val mappings =
        listOf(
            BuiltinIconMapping("AccountCircle", "AccountCircle", "person.crop.circle"),
            BuiltinIconMapping("AcUnit", "AcUnit", "snowflake"),
            BuiltinIconMapping("Add", "Add", "plus"),
            BuiltinIconMapping("AddCircle", "AddCircle", "plus.circle"),
            BuiltinIconMapping("Article", "Article", "doc.text"),
            BuiltinIconMapping("ArrowBack", "ArrowBack", "arrow.left"),
            BuiltinIconMapping("ArrowDownward", "ArrowDownward", "arrow.down"),
            BuiltinIconMapping("ArrowDropDown", "ArrowDropDown", "chevron.down"),
            BuiltinIconMapping("ArrowDropUp", "ArrowDropUp", "chevron.up"),
            BuiltinIconMapping("ArrowForward", "ArrowForward", "arrow.right"),
            BuiltinIconMapping("ArrowRight", "ArrowRight", "arrow.right"),
            BuiltinIconMapping("ArrowUpward", "ArrowUpward", "arrow.up"),
            BuiltinIconMapping("AudioFile", "AudioFile", "music.note"),
            BuiltinIconMapping("CalendarMonth", "CalendarMonth", "calendar"),
            BuiltinIconMapping("Calculate", "Calculate", "function"),
            BuiltinIconMapping("Call", "Call", "phone"),
            BuiltinIconMapping("Check", "Check", "checkmark"),
            BuiltinIconMapping("CheckCircle", "CheckCircle", "checkmark.circle"),
            BuiltinIconMapping("ChevronLeft", "ChevronLeft", "chevron.left"),
            BuiltinIconMapping("ChevronRight", "ChevronRight", "chevron.right"),
            BuiltinIconMapping("Clear", "Clear", "xmark.circle"),
            BuiltinIconMapping("Close", "Close", "xmark"),
            BuiltinIconMapping("Code", "Code", "chevron.left.forwardslash.chevron.right"),
            BuiltinIconMapping("ContentCopy", "ContentCopy", "doc.on.doc"),
            BuiltinIconMapping("Contacts", "Contacts", "person.2"),
            BuiltinIconMapping("Delete", "Delete", "trash"),
            BuiltinIconMapping("Description", "Description", "doc.text"),
            BuiltinIconMapping("DeviceThermostat", "DeviceThermostat", "thermometer"),
            BuiltinIconMapping("Done", "Done", "checkmark"),
            BuiltinIconMapping("Download", "Download", "arrow.down.circle"),
            BuiltinIconMapping("Edit", "Edit", "pencil"),
            BuiltinIconMapping("Error", "Error", "exclamationmark.circle"),
            BuiltinIconMapping("Favorite", "Favorite", "heart"),
            BuiltinIconMapping("FavoriteBorder", "FavoriteBorder", "heart"),
            BuiltinIconMapping("Folder", "Folder", "folder"),
            BuiltinIconMapping("FolderOpen", "FolderOpen", "folder"),
            BuiltinIconMapping("FolderZip", "FolderZip", "archivebox"),
            BuiltinIconMapping("GridView", "GridView", "square.grid.2x2"),
            BuiltinIconMapping("Help", "HelpOutline", "questionmark.circle"),
            BuiltinIconMapping("HelpOutline", "HelpOutline", "questionmark.circle"),
            BuiltinIconMapping("History", "History", "clock.arrow.circlepath"),
            BuiltinIconMapping("Home", "Home", "house"),
            BuiltinIconMapping("Image", "Image", "photo"),
            BuiltinIconMapping("Info", "Info", "info.circle"),
            BuiltinIconMapping("InfoOutline", "Info", "info.circle"),
            BuiltinIconMapping("InsertDriveFile", "InsertDriveFile", "doc"),
            BuiltinIconMapping("KeyboardArrowDown", "KeyboardArrowDown", "chevron.down"),
            BuiltinIconMapping("KeyboardArrowLeft", "KeyboardArrowLeft", "chevron.left"),
            BuiltinIconMapping("KeyboardArrowRight", "KeyboardArrowRight", "chevron.right"),
            BuiltinIconMapping("KeyboardArrowUp", "KeyboardArrowUp", "chevron.up"),
            BuiltinIconMapping("Link", "Link", "link"),
            BuiltinIconMapping("Lock", "Lock", "lock"),
            BuiltinIconMapping("LockOpen", "LockOpen", "lock.open"),
            BuiltinIconMapping("LocationCity", "LocationCity", "building.2"),
            BuiltinIconMapping("Mail", "Mail", "envelope"),
            BuiltinIconMapping("Menu", "Menu", "line.3.horizontal"),
            BuiltinIconMapping("Message", "Message", "message"),
            BuiltinIconMapping("MoreHoriz", "MoreHoriz", "ellipsis"),
            BuiltinIconMapping("MoreVert", "MoreVert", "ellipsis.vertical"),
            BuiltinIconMapping("Notifications", "Notifications", "bell"),
            BuiltinIconMapping("OpenInNew", "OpenInNew", "arrow.up.right.square"),
            BuiltinIconMapping("Pause", "Pause", "pause"),
            BuiltinIconMapping("Person", "Person", "person"),
            BuiltinIconMapping("PersonAdd", "PersonAdd", "person.badge.plus"),
            BuiltinIconMapping("Phone", "Phone", "phone"),
            BuiltinIconMapping("PictureAsPdf", "PictureAsPdf", "doc"),
            BuiltinIconMapping("PlayArrow", "PlayArrow", "play"),
            BuiltinIconMapping("Refresh", "Refresh", "arrow.clockwise"),
            BuiltinIconMapping("Save", "Save", "square.and.arrow.down"),
            BuiltinIconMapping("Search", "Search", "magnifyingglass"),
            BuiltinIconMapping("Settings", "Settings", "gearshape"),
            BuiltinIconMapping("Share", "Share", "square.and.arrow.up"),
            BuiltinIconMapping("Star", "Star", "star"),
            BuiltinIconMapping("StarBorder", "StarBorder", "star"),
            BuiltinIconMapping("Stop", "Stop", "stop"),
            BuiltinIconMapping("StickyNote2", "StickyNote2", "note.text"),
            BuiltinIconMapping("Sync", "Sync", "arrow.triangle.2.circlepath"),
            BuiltinIconMapping("Thunderstorm", "Thunderstorm", "cloud.bolt.rain"),
            BuiltinIconMapping("Today", "Today", "calendar"),
            BuiltinIconMapping("Tune", "Tune", "slider.horizontal.3"),
            BuiltinIconMapping("Upload", "Upload", "arrow.up.circle"),
            BuiltinIconMapping("VideoFile", "VideoFile", "video"),
            BuiltinIconMapping("Visibility", "Visibility", "eye"),
            BuiltinIconMapping("VisibilityOff", "VisibilityOff", "eye.slash"),
            BuiltinIconMapping("Warning", "Warning", "exclamationmark.triangle"),
            BuiltinIconMapping("WaterDrop", "WaterDrop", "drop"),
            BuiltinIconMapping("WbCloudy", "WbCloudy", "cloud"),
            BuiltinIconMapping("WbSunny", "WbSunny", "sun.max"),
            BuiltinIconMapping("Wifi", "Wifi", "wifi"),
        ).associateBy(BuiltinIconMapping::builtinName)

    fun materialIconName(name: String): String? = mappings[name]?.materialIconName

    fun sfSymbolName(name: String): String? = mappings[name]?.sfSymbolName

    val supportedNames: Set<String>
        get() = mappings.keys
}

data class BuiltinIconMapping(
    val builtinName: String,
    val materialIconName: String,
    val sfSymbolName: String,
)
